name: EternalFortune
version: ${plugin_version}
main: com.mineinabyss.eternalfortune.EternalFortune
api-version: "1.20"
authors: [ boy0000 ]
depend: [ Geary, Blocky, ProtocolBurrito ]

commands:
  eternalfortune:
    aliases: [ ef, eternal ]
